export type StageCodeSample = {
  file: string;
  language: "python" | "sql" | "typescript" | "text";
  status: "real" | "asset" | "not_connected";
  code: string;
};

const storageCode = [
  "def put_json(self, bucket: str, key: str, payload: Any) -> str:",
  "    self._ensure_bucket(bucket)",
  "    body = json.dumps(payload, ensure_ascii=False, default=str).encode(\"utf-8\")",
  "    self.client.put_object(",
  "        Bucket=bucket, Key=key, Body=body, ContentType=\"application/json\"",
  "    )",
  "    return f\"s3://{bucket}/{key}\"",
].join("\n");

export const stageCodeSamples: Record<string, StageCodeSample> = {
  fastapi: {
    file: "backend/app/main.py",
    language: "python",
    status: "real",
    code: [
      "@app.post(\"/pipeline/run\", response_model=PipelineRunResult)",
      "async def run_pipeline(request: PipelineRunRequest) -> PipelineRunResult:",
      "    runner = PipelineRunner(settings)",
      "    result = await runner.run(request)",
      "    PIPELINE_RUNS.labels(request.source, request.mode).inc()",
      "    return result",
    ].join("\n"),
  },
  nifi: {
    file: "nifi/create_dummyjson_flow.py",
    language: "python",
    status: "asset",
    code: [
      "invoke_http = client.create_processor(",
      "    group_id,",
      "    \"Fetch DummyJSON Source\",",
      "    \"org.apache.nifi.processors.standard.InvokeHTTP\",",
      "    120, 120,",
      "    {\"HTTP Method\": \"GET\", \"Remote URL\": args.dummyjson_url},",
      ")",
    ].join("\n"),
  },
  kafka: {
    file: "backend/app/kafka_bus.py",
    language: "python",
    status: "real",
    code: [
      "def publish(self, topic: str, event: dict[str, Any]) -> str:",
      "    producer = self._get_producer()",
      "    future = producer.send(topic, event)",
      "    metadata = future.get(timeout=10)",
      "    producer.flush(timeout=10)",
      "    return f\"kafka://{metadata.topic}/{metadata.partition}/{metadata.offset}\"",
    ].join("\n"),
  },
  landing: { file: "backend/app/storage.py", language: "python", status: "real", code: storageCode },
  raw: { file: "backend/app/storage.py", language: "python", status: "real", code: storageCode },
  preparation: {
    file: "backend/app/preparation.py",
    language: "python",
    status: "real",
    code: [
      "prepared = deepcopy(rows)",
      "for row in prepared:",
      "    for column, value in list(row.items()):",
      "        if isinstance(value, str):",
      "            row[column] = value.strip() or None",
      "",
      "for correction in corrections:",
      "    target = rows_by_id.get(str(correction[\"record_id\"]))",
      "    target[correction[\"column\"]] = coerce_value(",
      "        correction.get(\"value\"), target.get(correction[\"column\"])",
      "    )",
    ].join("\n"),
  },
  gx: {
    file: "backend/app/quality.py",
    language: "python",
    status: "real",
    code: [
      "checks = [",
      "    QualityCheck(name=\"record_count\", passed=total > 0, value=f\"{total} rows\"),",
      "    QualityCheck(name=\"primary_key\", passed=has_id == total, value=f\"{has_id}/{total}\"),",
      "    QualityCheck(name=\"schema_not_empty\", passed=has_data == total, value=f\"{has_data}/{total}\"),",
      "    QualityCheck(name=\"null_threshold\", passed=null_safe / total >= 0.9, value=f\"{null_safe}/{total}\"),",
      "]",
      "score = round(sum(1 for check in checks if check.passed) / len(checks) * 100)",
    ].join("\n"),
  },
  spark: {
    file: "backend/app/transform.py + spark/jobs/dummyjson_curate.py",
    language: "python",
    status: "real",
    code: [
      "base = {",
      "    \"dw_id\": f\"{source_id}_{row.get('id')}\",",
      "    \"run_id\": run_id,",
      "    \"source_system\": source_title,",
      "    \"ingestion_mode\": mode,",
      "}",
      "record = {**base, \"entity_name\": row.get(\"title\"),",
      "          \"metric_name\": \"price\", \"metric_value\": float(row.get(\"price\") or 0)}",
    ].join("\n"),
  },
  curated: { file: "backend/app/storage.py", language: "python", status: "real", code: storageCode },
  clickhouse: {
    file: "backend/app/databases.py",
    language: "python",
    status: "real",
    code: [
      "client = clickhouse_connect.get_client(",
      "    host=self.settings.clickhouse_host,",
      "    database=self.settings.clickhouse_database,",
      ")",
      "client.insert(\"curated_events\", data, column_names=columns)",
      "return f\"clickhouse://curated_events?rows={len(rows)}\"",
    ].join("\n"),
  },
  postgres: {
    file: "backend/app/databases.py",
    language: "sql",
    status: "real",
    code: [
      "insert into pipeline_runs",
      "  (run_id, source, mode, status, records, quality_score, warnings)",
      "values",
      "  (%(run_id)s, %(source)s, %(mode)s, %(status)s, %(records)s, %(quality_score)s, %(warnings)s::jsonb)",
      "on conflict (run_id) do update set",
      "  status = excluded.status,",
      "  quality_score = excluded.quality_score,",
      "  updated_at = now();",
    ].join("\n"),
  },
  airflow: {
    file: "airflow/dags/dwh_dummyjson_pipeline.py",
    language: "python",
    status: "asset",
    code: [
      "@dag(dag_id=\"dwh_dummyjson_pipeline\", schedule=\"@hourly\", catchup=False)",
      "def dwh_dummyjson_pipeline():",
      "    @task",
      "    def run_gateway(source: str, limit: int, mode: str) -> dict:",
      "        response = requests.post(f\"{FASTAPI_URL}/pipeline/run\",",
      "                                 json={\"source\": source, \"limit\": limit, \"mode\": mode})",
      "        response.raise_for_status()",
      "        return response.json()",
    ].join("\n"),
  },
  dbt: {
    file: "dbt/dwh_project/models/marts/fct_source_metrics.sql",
    language: "sql",
    status: "asset",
    code: [
      "select",
      "  source_entity, category, metric_name,",
      "  toDate(loaded_at) as load_date,",
      "  count() as record_count,",
      "  sum(metric_value) as metric_sum,",
      "  avg(metric_value) as metric_avg",
      "from {{ ref('stg_curated_events') }}",
      "group by source_entity, category, metric_name, load_date",
    ].join("\n"),
  },
  superset: {
    file: "NOT CONNECTED",
    language: "text",
    status: "not_connected",
    code: "Superset service va dataset konfiguratsiyasi hali repositoryga ulanmagan.\nClickHouse curated_events jadvali BI dataset uchun tayyor.",
  },
  trino: {
    file: "NOT CONNECTED",
    language: "text",
    status: "not_connected",
    code: "Trino service, catalog va connector konfiguratsiyasi hali compose ichida mavjud emas.",
  },
  api: {
    file: "frontend/app/api/backend/pipeline/run/route.ts",
    language: "typescript",
    status: "asset",
    code: [
      "export async function POST(request: Request) {",
      "  const body = await request.text();",
      "  return proxyJson(\"/pipeline/run\", {",
      "    method: \"POST\",",
      "    body,",
      "  });",
      "}",
    ].join("\n"),
  },
  portal: {
    file: "frontend/components/Dashboard.tsx",
    language: "typescript",
    status: "asset",
    code: [
      "const nextResult = await fetchJson<PipelineResult>(",
      "  \"/api/backend/pipeline/run\",",
      "  { method: \"POST\", body: JSON.stringify({ source, limit, mode, failure_stage, corrections }) },",
      ");",
      "setResult(nextResult);",
      "startStagePlayback(nextResult);",
    ].join("\n"),
  },
  export: {
    file: "NOT CONNECTED",
    language: "text",
    status: "not_connected",
    code: "JSON response real ishlaydi. CSV, Excel va PDF export endpointlari hali implement qilinmagan.",
  },
};
